/**
 * APT Group Configuration
 * State-sponsored threat actor data for map markers and intelligence panels.
 * Source: MITRE ATT&CK Groups (https://attack.mitre.org/groups/)
 */

import type { APTGroup } from '@/types';

export const APT_GROUPS: APTGroup[] = [
  // ===== RUSSIA =====
  {
    id: 'apt28',
    name: 'APT28',
    aliases: ['Fancy Bear', 'Sofacy', 'Sednit', 'STRONTIUM', 'Forest Blizzard'],
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    sponsor: 'GRU Unit 26165',
    targetSectors: ['government', 'military', 'energy', 'media', 'defence'],
    targetCountries: ['US', 'EU', 'UA', 'GE', 'NATO'],
    techniques: ['T1566', 'T1190', 'T1078', 'T1059'],
    mitreId: 'G0007',
    activeSince: '2004',
    description: 'Russian military intelligence (GRU) cyber espionage group targeting government, military, and critical infrastructure.',
  },
  {
    id: 'apt29',
    name: 'APT29',
    aliases: ['Cozy Bear', 'The Dukes', 'NOBELIUM', 'Midnight Blizzard'],
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    sponsor: 'SVR (Foreign Intelligence Service)',
    targetSectors: ['government', 'think-tanks', 'healthcare', 'technology', 'diplomatic'],
    targetCountries: ['US', 'EU', 'UK', 'NATO'],
    techniques: ['T1195.002', 'T1566.001', 'T1078', 'T1021'],
    mitreId: 'G0016',
    activeSince: '2008',
    description: 'Russian foreign intelligence service (SVR) espionage group known for sophisticated supply chain attacks.',
  },
  {
    id: 'sandworm',
    name: 'Sandworm',
    aliases: ['Voodoo Bear', 'IRIDIUM', 'Seashell Blizzard', 'TeleBots'],
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    sponsor: 'GRU Unit 74455',
    targetSectors: ['energy', 'government', 'media', 'transport', 'critical-infrastructure'],
    targetCountries: ['UA', 'US', 'EU', 'GE', 'KR'],
    techniques: ['T1059', 'T1486', 'T1498', 'T1565'],
    mitreId: 'G0034',
    activeSince: '2009',
    description: 'Destructive Russian military intelligence group responsible for NotPetya, Ukraine power grid attacks, and Olympic Destroyer.',
  },
  {
    id: 'turla',
    name: 'Turla',
    aliases: ['Snake', 'Venomous Bear', 'KRYPTON', 'Secret Blizzard'],
    country: 'Russia',
    countryCode: 'RU',
    lat: 55.7558,
    lng: 37.6173,
    sponsor: 'FSB Center 16',
    targetSectors: ['government', 'military', 'research', 'diplomatic', 'aerospace'],
    targetCountries: ['US', 'EU', 'Central Asia', 'Middle East'],
    techniques: ['T1071', 'T1055', 'T1547', 'T1027'],
    mitreId: 'G0010',
    activeSince: '1996',
    description: 'Sophisticated Russian FSB cyber espionage group with one of the longest operational histories.',
  },

  // ===== CHINA =====
  {
    id: 'apt41',
    name: 'APT41',
    aliases: ['Winnti', 'Double Dragon', 'Wicked Panda', 'Brass Typhoon'],
    country: 'China',
    countryCode: 'CN',
    lat: 30.5728,
    lng: 104.0668,
    sponsor: 'MSS / Chengdu',
    targetSectors: ['gaming', 'healthcare', 'telecom', 'technology', 'education'],
    targetCountries: ['US', 'EU', 'Asia-Pacific', 'IN'],
    techniques: ['T1195', 'T1190', 'T1059', 'T1505'],
    mitreId: 'G0096',
    activeSince: '2012',
    description: 'Dual espionage and financially motivated group conducting supply chain attacks and intellectual property theft.',
  },
  {
    id: 'apt10',
    name: 'APT10',
    aliases: ['Stone Panda', 'menuPass', 'Red Apollo', 'Cicada'],
    country: 'China',
    countryCode: 'CN',
    lat: 31.2304,
    lng: 121.4737,
    sponsor: 'MSS Tianjin Bureau',
    targetSectors: ['MSPs', 'government', 'defence', 'aerospace', 'telecom'],
    targetCountries: ['US', 'JP', 'UK', 'AU', 'EU'],
    techniques: ['T1199', 'T1566', 'T1071', 'T1027'],
    mitreId: 'G0045',
    activeSince: '2006',
    description: 'Chinese espionage group known for Operation Cloud Hopper targeting managed service providers.',
  },
  {
    id: 'volt_typhoon',
    name: 'Volt Typhoon',
    aliases: ['Bronze Silhouette', 'Vanguard Panda', 'DEV-0391'],
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    sponsor: 'PLA',
    targetSectors: ['critical-infrastructure', 'telecom', 'government', 'maritime', 'energy'],
    targetCountries: ['US', 'GU', 'Pacific Islands'],
    techniques: ['T1133', 'T1059', 'T1078', 'T1003'],
    mitreId: 'G1017',
    activeSince: '2021',
    description: 'Chinese state group pre-positioning on US critical infrastructure using living-off-the-land techniques.',
  },
  {
    id: 'salt_typhoon',
    name: 'Salt Typhoon',
    aliases: ['GhostEmperor', 'FamousSparrow'],
    country: 'China',
    countryCode: 'CN',
    lat: 39.9042,
    lng: 116.4074,
    sponsor: 'MSS',
    targetSectors: ['telecom', 'ISPs', 'government'],
    targetCountries: ['US', 'EU', 'Southeast Asia'],
    techniques: ['T1190', 'T1505', 'T1071', 'T1560'],
    mitreId: 'G1045',
    activeSince: '2019',
    description: 'Chinese espionage group targeting telecommunications infrastructure for surveillance access.',
  },

  // ===== NORTH KOREA =====
  {
    id: 'lazarus',
    name: 'Lazarus Group',
    aliases: ['Hidden Cobra', 'Zinc', 'Diamond Sleet', 'Labyrinth Chollima'],
    country: 'North Korea',
    countryCode: 'KP',
    lat: 39.0392,
    lng: 125.7625,
    sponsor: 'RGB (Reconnaissance General Bureau)',
    targetSectors: ['finance', 'cryptocurrency', 'defence', 'aerospace', 'entertainment'],
    targetCountries: ['US', 'KR', 'JP', 'Global'],
    techniques: ['T1566', 'T1059', 'T1486', 'T1071'],
    mitreId: 'G0032',
    activeSince: '2009',
    description: 'North Korean state group conducting financially motivated attacks and destructive operations (Sony, WannaCry, bank heists).',
  },
  {
    id: 'kimsuky',
    name: 'Kimsuky',
    aliases: ['Velvet Chollima', 'Thallium', 'Emerald Sleet', 'Black Banshee'],
    country: 'North Korea',
    countryCode: 'KP',
    lat: 39.0392,
    lng: 125.7625,
    sponsor: 'RGB',
    targetSectors: ['think-tanks', 'nuclear', 'government', 'academic', 'media'],
    targetCountries: ['KR', 'US', 'JP', 'EU'],
    techniques: ['T1566', 'T1204', 'T1059', 'T1053'],
    mitreId: 'G0094',
    activeSince: '2012',
    description: 'North Korean espionage group focused on intelligence gathering around nuclear policy and sanctions.',
  },

  // ===== IRAN =====
  {
    id: 'apt33',
    name: 'APT33',
    aliases: ['Elfin', 'Magnallium', 'Holmium', 'Peach Sandstorm', 'Refined Kitten'],
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    sponsor: 'IRGC (Islamic Revolutionary Guard Corps)',
    targetSectors: ['aviation', 'energy', 'petrochemical', 'defence'],
    targetCountries: ['US', 'SA', 'KR', 'EU'],
    techniques: ['T1566', 'T1110', 'T1059', 'T1078'],
    mitreId: 'G0064',
    activeSince: '2013',
    description: 'Iranian IRGC-linked group targeting aviation and energy sectors in the US, Saudi Arabia, and allies.',
  },
  {
    id: 'apt34',
    name: 'APT34',
    aliases: ['OilRig', 'Helix Kitten', 'Hazel Sandstorm', 'Crambus'],
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    sponsor: 'MOIS (Ministry of Intelligence)',
    targetSectors: ['government', 'financial', 'telecom', 'energy', 'chemical'],
    targetCountries: ['Middle East', 'US', 'EU'],
    techniques: ['T1566', 'T1059', 'T1071', 'T1027'],
    mitreId: 'G0049',
    activeSince: '2014',
    description: 'Iranian intelligence group conducting espionage against regional governments and critical infrastructure.',
  },
  {
    id: 'apt35',
    name: 'APT35',
    aliases: ['Charming Kitten', 'Phosphorus', 'Mint Sandstorm', 'NewsBeef'],
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    sponsor: 'IRGC Intelligence Organization',
    targetSectors: ['academia', 'media', 'government', 'human-rights', 'technology'],
    targetCountries: ['US', 'IL', 'UK', 'Middle East'],
    techniques: ['T1566', 'T1204', 'T1078', 'T1059'],
    mitreId: 'G0059',
    activeSince: '2014',
    description: 'Iranian IRGC-linked group targeting journalists, activists, and government officials via social engineering.',
  },
  {
    id: 'muddywater',
    name: 'MuddyWater',
    aliases: ['Mercury', 'Mango Sandstorm', 'Static Kitten', 'Seedworm'],
    country: 'Iran',
    countryCode: 'IR',
    lat: 35.6892,
    lng: 51.3890,
    sponsor: 'MOIS',
    targetSectors: ['telecom', 'government', 'oil-gas', 'defence', 'IT'],
    targetCountries: ['Middle East', 'South Asia', 'EU', 'US'],
    techniques: ['T1566', 'T1059', 'T1053', 'T1219'],
    mitreId: 'G0069',
    activeSince: '2017',
    description: 'Iranian intelligence group targeting Middle Eastern telecom and government networks.',
  },
];

// Country aggregation helper
export function getAPTsByCountry(): Record<string, APTGroup[]> {
  const grouped: Record<string, APTGroup[]> = {};
  for (const apt of APT_GROUPS) {
    if (!grouped[apt.country]) grouped[apt.country] = [];
    grouped[apt.country].push(apt);
  }
  return grouped;
}

// Sector search helper
export function getAPTsBySector(sector: string): APTGroup[] {
  return APT_GROUPS.filter((apt) =>
    apt.targetSectors.some((s) => s.toLowerCase().includes(sector.toLowerCase()))
  );
}
